////
Copyright (c) 2024 The C++ Alliance, Inc. (https://cppalliance.org)

Distributed under the Boost Software License, Version 1.0. (See accompanying
file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

Official repository: https://github.com/boostorg/website-v2-docs
////
= Counted Body Techniques
:navtitle: Counted Body

Reference counting techniques? Nothing new, you might think. Every good pass:[C++] text that takes you to an intermediate or advanced level will introduce the concept. It has been explored with such thoroughness in the past that you might be forgiven for thinking that everything that can be said has been said. Well, let's start from first principles and see if we can unearth something new....

== And Then There Were None...

The principle behind reference counting is to keep a running usage count of an object so that when it falls to zero we know the object is unused. This is normally used to simplify the memory management for dynamically allocated objects: keep a count of the number of references held to that object and, on zero, delete the object.

How to keep a track of the number of users of an object? Well, normal pointers are quite dumb, and so an extra level of indirection is required to manage the count. This is essentially the _proxy_ pattern described in _Design Patterns [Gamma, Helm, Johnson & Vlissides, Addison-Wesley, ISBN 0-201-63361-2]_. The intent is given as _"Provide a surrogate or placeholder for another object to control access to it."_

_Advanced C++ Programming Styles and Idioms [Coplien, Addison-Wesley, ISBN 0-201-56365-7]_ defines a set of idioms related to this essential separation of a handle and a body part. The _Taligent Guide to Designing Programs [Addison-Wesley, ISBN 0-201-40888-0]_ identifies a number of specific categories for proxies (aka surrogates). Broadly speaking they fall into two general categories:

. _Hidden_: The handle is the object of interest, hiding the body itself. The functionality of the handle is obtained by delegation to the body, and the user of the handle is unaware of the body. Reference counted strings offer a transparent optimization. The body is shared between copies of a string until such a time as a change is needed, at which point a copy is made. Such a _copy-on-write_ pattern (a specialization of _lazy evaluation_) requires the use of a hidden reference counted body.
. _Explicit_: Here the body is of interest and the handle merely provides intelligence for its access and housekeeping. In pass:[C++] this is often implemented as the _smart pointer_ idiom. One such application is that of reference-counted smart pointers that collaborate to keep a count of an object, deleting it when the count falls to zero.

== Attached vs Detached

For reference counted smart pointers there are two places the count can exist, resulting in two different patterns, both outlined in _Software Patterns [Coplien, SIGS, ISBN 0-884842-50-X]_:

* _Counted body_ or _attached counted handle/body_ places the count within the object being counted. The benefits are that countability is a part of the object being counted, and that reference counting does not require an additional object. The drawbacks are clearly that this is intrusive, and that the space for the reference count is wasted when the object is not heap-based. Therefore the reference counting ties you to a particular implementation and style of use.
* _Detached counted handle/body_ places the count outside the object being counted, such that they are handled together. The clear benefit of this is that this technique is completely unintrusive, with all of the intelligence and support apparatus in the smart pointer, and therefore can be used on classes created independently of the reference counted pointer. The main disadvantage is that frequent use of this can lead to a proliferation of small objects, i.e. the counter, being created on the heap.

Even with this simple analysis, it seems that the _Detached counted handle/body_ approach is ahead. Indeed, with the increasing use of templates this is often the favorite, and is the principle behind the common - but not standard - `counted_ptr`.

Note:: The Boost name is `shared_ptr` rather than `counted_ptr`.

A common implementation of _counted body_ is to provide the counting mechanism in a base class that the counted type is derived from. Either that, or the reference counting mechanism is provided anew for each class that needs it. Both of these approaches are unsatisfactory because they are quite closed, coupling a class into a particular framework. Added to this the non-cohesiveness of having the count lying dormant in a non-counted object, and you get the feeling that excepting its use in widespread object models such as https://en.wikipedia.org/wiki/Component_Object_Model[COM] and https://en.wikipedia.org/wiki/Common_Object_Request_Broker_Architecture[CORBA] the _counted body_ approach is perhaps only of use in specialized situations.

== A Requirements Based Approach

It is the question of openness that convinced me to revisit the problems with the _counted body_ idiom. Yes, there is a certain degree of intrusion expected when using this idiom, but is there anyway to minimize this and decouple the choice of counting mechanism from the smart pointer type used?

In recent years the most instructive body of code and specification for constructing open general purpose components has been the Stepanov and Lee's STL (Standard Template Library), now part of the pass:[C++] standard library. The STL approach makes extensive use of compile time polymorphism based on well defined operational requirements for types. For instance, each container, contained and iterator type is defined by the operations that should be performable on an object of that type, often with annotations describing additional constraints. Compile time polymorphism, as its name suggests, resolves functions at compile time based on function name and argument usage, i.e. overloading. This is less intrusive, although less easily diagnosed if incorrect, than runtime polymorphism that is based on types, names and function signatures.

This requirements based approach can be applied to reference counting. The operations we need for a type to be _countable_ are loosely:

. An acquire operation that registers interest in a countable object.
. A release operation unregisters interest in a countable object.
. An acquired query that returns whether or not a countable object is currently acquired.
. A dispose operation that is responsible for disposing of an object that is no longer acquired.

Note:: The count is deduced as a part of the abstract state of this type, and is not mentioned or defined in any other way. The openness of this approach derives in part from the use of global functions, meaning that no particular member functions are implied; a perfect way to wrap up an existing counted body class without modifying the class itself. The other aspect of openness comes from a more precise specification of the operations.

For a type to be countable it must satisfy the following requirements, where `ptr` is a non-null pointer to a single object (i.e. not an array) of the type, and `#function` indicates number of calls to `function(ptr)`:

[cols="1,1,2",options="header",stripes=even,frame=none]
|===
| *Expression* | *Return type* | *Semantics and notes*
| `acquire(ptr)` | no requirement | _post_: `acquired(ptr)`
| `release(ptr)` | no requirement | _pre_: `acquired(ptr)` _post_: `acquired(ptr) == #acquire - #release`
| `acquired(ptr)` | convertible to bool | return: `#acquire > #release`
| `dispose(ptr, ptr)` | no requirement | _pre_: `!acquired(ptr)` _post_: `*ptr` no longer usable
|===

Note:: The two arguments to `dispose` are to support selection of the appropriate type-safe version of the function to be called. In the general case the intent is that the first argument determines the type to be deleted, and would typically be templated, while the second selects which template to use, for example: by conforming to a specific base class.

In addition the following requirements must also be satisfied, where `null` is a null pointer to the countable type:

[cols="1,1,2",options="header",stripes=even,frame=none]
|===
| *Expression* | *Return type* | *Semantics and notes*
| `acquire(null)` | no requirement | _action_: none
| `release(null)` | no requirement | _action_: none
| `acquired(null)` | convertible to `bool` | _return_: `false`
| `dispose(null, null)` | no requirement | _action_: none
|===

Note:: There are no requirements on these functions in terms of exceptions thrown or not thrown, except that if exceptions are thrown the functions themselves should be exception-safe.

== Getting Smart

Given the countable requirements for a type, it is possible to define a generic smart pointer type that uses them for reference counting:

```cpp
template<typename countable_type>
class countable_ptr
{
public: // construction and destruction

    explicit countable_ptr(countable_type *);
    countable_ptr(const countable_ptr &);
    ~countable_ptr();

public: // access

    countable_type *operator->() const;
    countable_type &operator*() const;
    countable_type *get() const;

public: // modification

    countable_ptr &clear();
    countable_ptr &assign(countable_type *);
    countable_ptr &assign(const countable_ptr &);
    countable_ptr &operator=(const countable_ptr &);

private: // representation

    countable_type *body;

};
```

The interface to this class has been kept intentionally simple, for example: member templates and throw specs have been omitted, for exposition. The majority of the functions are quite simple in implementation, relying very much on the assign member as a keystone function:

```cpp
template<typename countable_type>
countable_ptr<countable_type>::countable_ptr(countable_type *initial)
  : body(initial)
{
    acquire(body);
}

template<typename countable_type>
countable_ptr<countable_type>::countable_ptr(const countable_ptr &other)
  : body(other.body)
{
    acquire(body);
}

template<typename countable_type>
countable_ptr<countable_type>::~countable_ptr()
{
    clear();
}

template<typename countable_type>
countable_type *countable_ptr<countable_type>::operator->() const
{
    return body;
}

template<typename countable_type>
countable_type &countable_ptr<countable_type>::operator*() const
{
    return *body;
}

template<typename countable_type>
countable_type *countable_ptr<countable_type>::get() const
{
    return body;
}

template<typename countable_type>
countable_ptr<countable_type> &countable_ptr<countable_type>::clear()
{
    return assign(0);
}

template<typename countable_type>
countable_ptr<countable_type> &countable_ptr<countable_type>::assign(countable_type *rhs)
{
    // set to rhs (uses Copy Before Release idiom which is self assignment safe)
    acquire(rhs);
    countable_type *old_body = body;
    body = rhs;

    // tidy up
    release(old_body);
    if(!acquired(old_body))
    {
        dispose(old_body, old_body);
    }

    return *this;
}

template<typename countable_type>
countable_ptr<countable_type> &countable_ptr<countable_type>::assign(const countable_ptr &rhs)
{
    return assign(rhs.body);
}

template<typename countable_type>
countable_ptr<countable_type> &countable_ptr<countable_type>::operator=(const countable_ptr &rhs)
{
    return assign(rhs);
}
```

== Public Accountability

Conformance to the requirements means that a type can be used with `countable_ptr`. Here is an implementation _mix-in_ class that confers countability on its derived classes through member functions. This class can be used as a class adaptor:

```cpp
class countability
{
public: // manipulation

    void acquire() const;
    void release() const;
    size_t acquired() const;

protected: // construction and destruction

    countability();
    ~countability();

private: // representation

    mutable size_t count;

private: // prevention

    countability(const countability &);
    countability &operator=(const countability &);

};
```

Note:: The manipulation functions are `const` and that the count member itself is mutable. This is because countability is not a part of an object's abstract state: memory management does not depend on the const-ness or otherwise of an object. I won't include the definitions of the member functions here as you can probably guess them: increment, decrement, and return the current count, respectively for the manipulation functions. In a multithreaded environment, you should ensure that such read and write operations are atomic.

So how do we make this class countable? A simple set of forwarding functions does the job:

```cpp
void acquire(const countability *ptr)
{
    if(ptr)
    {
        ptr->acquire();
    }
}

void release(const countability *ptr)
{
    if(ptr)
    {
        ptr->release();
    }
}

size_t acquired(const countability *ptr)
{
    return ptr ? ptr->acquired() : 0;
}

template<class countability_derived>
void dispose(const countability_derived *ptr, const countability *)
{
    delete ptr;
}
Any type that now derives from countability may now be used with countable_ptr:

class example : public countability
{
    ...
};

void simple()
{
    countable_ptr<example> ptr(new example);
    countable_ptr<example> qtr(ptr);
    ptr.clear(); // set ptr to point to null
}   // allocated object deleted when qtr destructs
```

== Runtime Mixin

The challenge is to apply _counted body_ in a non-intrusive fashion, such that there is no overhead when an object is not counted. What we would like to do is confer this capability on a per object rather than on a per class basis. Effectively we are after _countability_ on any object, i.e. anything pointed to by a `void *`! It goes without saying that `void` is perhaps the least committed of any type.

The forces to resolve this are quite interesting, to say the least. Interesting, but not insurmountable. Given that the class of a runtime object cannot change dynamically in any well defined manner, and the layout of the object must be fixed, we have to find a new place and time to add the counting state. The fact that this must be added only on heap creation suggests the following solution:

```cpp
struct countable_new;
extern const countable_new countable;

void *operator new(size_t, const countable_new &);
void operator delete(void *, const countable_new &);
```

We have overloaded `operator new` with a dummy argument to distinguish it from the regular global operator `new`. This is comparable to the use of the `std::nothrow_t` type and `std::nothrow` object in the standard library. The placement `operator delete` is there to perform any tidy up in the event of failed construction. Note that this is not yet supported on all compilers.

The result of a `new` expression using `countable` is an object allocated on the heap that has a header block that holds the count, i.e. we have extended the object by prefixing it. We can provide a couple of features in an anonymous namespace (not shown) in the implementation file for supporting the count and its access from a raw pointer:

```cpp
struct count
{
    size_t value;
};

count *header(const void *ptr)
{
    return const_cast<count *>(static_cast<const count *>(ptr) - 1);
}
```

An important constraint to observe here is the alignment of `count` should be such that it is suitably aligned for any type. For the definition shown this will be the case on almost all platforms. However, you may need to add a padding member for those that don't, for example: using an anonymous `union` to co-align `count` and the most aligned type. Unfortunately, there is no portable way of specifying this such that the minimum alignment is also observed - this is a common problem when specifying your own allocators that do not directly use the results of either `new` or `malloc`.

Again, note that the count is not considered to be a part of the logical state of the object, and hence the conversion from `const` to non-const - count is in effect a mutable type.

The allocator functions themselves are fairly straightforward:

```cpp
void *operator new(size_t size, const countable_new &)
{
    count *allocated = static_cast<count *>(::operator new(sizeof(count) + size));
    *allocated = count(); // initialise the header
    return allocated + 1; // adjust result to point to the body
}

void operator delete(void *ptr, const countable_new &)
{
    ::operator delete(header(ptr));
}
```

Given a correctly allocated header, we now need the countable functions to operate on `const void *` to complete the picture:

```cpp
void acquire(const void *ptr)
{
    if(ptr)
    {
        ++header(ptr)->value;
    }
}

void release(const void *ptr)
{
    if(ptr)
    {
        --header(ptr)->value;
    }
}

size_t acquired(const void *ptr)
{
    return ptr ? header(ptr)->value : 0;
}

template<typename countable_type>
void dispose(const countable_type *ptr, const void *)
{
    ptr->~countable_type();
    operator delete(const_cast<countable_type *>(ptr), countable);
}
```

The most complex of these is the dispose function that must ensure that the correct type is destructed and also that the memory is collected from the correct offset. It uses the value and type of first argument to perform this correctly, and the second argument merely acts as a strategy selector, i.e. the use of `const void *` distinguishes it from the earlier `dispose` shown for `const countability *`.

== Getting Smarter

Now that we have a way of adding countability at creation for objects of any type, what extra is needed to make this work with the `countable_ptr` we defined earlier? Good news: nothing!

```cpp
class example
{
    ...
};

void simple()
{
    countable_ptr<example> ptr(new(countable) example);
    countable_ptr<example> qtr(ptr);
    ptr.clear(); // set ptr to point to null
}   // allocated object deleted when qtr destructs
```

The `new(countable)` expression defines a different policy for allocation and de-allocation and, in common with other allocators, any attempt to mix your allocation policies, for example: call `delete` on an object allocated with `new(countable)`, results in undefined behavior. This is similar to what happens when you mix `new[]` with `delete` or `malloc` with `delete`. The whole point of countable conformance is that countable objects are used with `countable_ptr`, and this ensures the correct use.

However, accidents will happen, and inevitably you may forget to allocate using `new(countable)` and instead use `new`. This error and others can be detected in most cases by extending the code shown here to add a check member to the count, validating the check on every access. A benefit of ensuring clear separation between header and implementation source files mean that you can introduce a checking version of this allocator without having to recompile your code.

== Conclusion

There are two key concepts that this article has introduced:

* The use of a generic requirements based approach to simplify and adapt the use of the _counted body_ pattern.
* The ability, through control of allocation, to dynamically and non-intrusively add capabilities to fixed types using the _runtime mixin_ pattern.

The application of the two together gives rise to a new variant of the essential _counted body_ pattern: _unintrusive counted body_. You can take this theme even further and contrive a simple garbage collection system for pass:[C++].

== Acknowledgements

This topic was originally written as a paper by Kevlin Henney, and first published in _Overload 25, April 1998, ISSN 1354-3172_.

== See Also

For different approaches to reference counting in Boost libraries, refer to:

* boost:smart_ptr[] : provides support for `shared_ptr` and `weak_ptr`.
* boost:intrusive[] : provides support for `intrusive_ptr` and `shared_ptr`.
* boost:graph[] : provides support for `adjacency_list`.
* boost:interprocess[] : provides support for `interprocess_ptr`.
