= Use Boost with Linux and a Package Manager
:navtitle: Boost Linux Package Manager

Depending on your version of Unix, you can use a package manager such as *apt*, *dnf*, *yum*, or *pacman*. You can also install and use the *vcpkg* package manager.

== To Install Boost onto Debian-based Systems

To install the Boost C++ libraries onto Debian-based systems (such as Debian, Ubuntu), you can use the package manager *apt*. Follow these steps to install the Boost libraries:

. Open a terminal window.

. Update your package manager's repository cache. Use the following command: 

+
[source]
----
`sudo apt update`
----

. Install the Boost development libraries using your package manager. For Ubuntu or Debian-based distributions, you can use the following command: 

+
[source]
----
`sudo apt install libboost-all-dev`
----

+
This command installs all the Boost development libraries available in the package repository.

. <<Verify your Boost Installation>>.

== To Install Boost onto Fedora

To install the Boost C++ libraries on Fedora, you can use the package manager *dnf*. The Boost libraries are usually available as pre-compiled packages in the official Fedora repositories. Follow these steps to install the Boost libraries:

. Open a terminal window.

. Update your package list to ensure you're getting the most recent version of the Boost libraries available in the repositories:

+
[source]
----
sudo dnf update
----

. Install the Boost development libraries by running:
+
[source]
----
sudo dnf install boost-devel
----
+
This command installs the core Boost libraries and their development files. If you need additional libraries, you can search for specific Boost packages using the *dnf* search command, and install them individually.

. <<Verify your Boost Installation>>.

== To Install Boost onto CentOS

To install the Boost C++ libraries on CentOS, you can use the package manager *yum*. The Boost libraries are usually available as pre-compiled packages in the official CentOS repositories. Follow these steps to install the Boost libraries:

. Open a terminal window.

+
Note::
 If you are using CentOS 8 or later, you might need to enable the PowerTools repository to get the Boost development libraries:

+
[source]
----
sudo yum config-manager --set-enabled powertools
----

. Update your package list to ensure you're getting the most recent version of the Boost libraries available in the repositories:

+
[source]
----
sudo yum update
----

. Install the Boost development libraries by running:
+
[source]
----
sudo yum install boost-devel
----
+
This command installs the core Boost libraries and their development files. If you need additional libraries, you can search for specific Boost packages using the *yum* search command, and install them individually.

. <<Verify your Boost Installation>>.

== To Install Boost onto Arch-based Systems

To install the Boost C++ libraries onto Arch-based systems (such as Arch Linux, Manjaro), you can use the package manager *pacman*. Follow these steps to install the Boost libraries:

. Open a terminal window.

. Update your package list to ensure you're getting the most recent version of the Boost libraries available in the repositories:

+
[source]
----
sudo pacman -Syu
----

. Install the Boost development libraries by running:
+
[source]
----
sudo pacman -S boost
----

. <<Verify your Boost Installation>>.

== To Install Boost with the vcpkg Package Manager

You can use vcpkg on Linux. To install vcpkg on a Linux system, follow these steps:

. Open a terminal. Install the necessary packages for building vcpkg by running the following command (for Ubuntu or Debian-based systems):

+
[source]
----
sudo apt-get update
sudo apt-get install build-essential tar curl zip unzip git
----

+
For other Linux distributions, install the equivalent packages using the appropriate package manager, such as _yum_, _dnf_, or _pacman_.

. Clone the vcpkg repository from GitHub by running the following command:

+
[source]
----
git clone https://github.com/microsoft/vcpkg.git
----
 
+ 
This command will create a new directory named "vcpkg" in your current directory and clone the repository into it.

. Change to the *vcpkg* directory: `cd vcpkg`. Then run the bootstrap script to build the vcpkg executable: 

+
[source]
----
./bootstrap-vcpkg.sh
----

+
This script will download and build the necessary components for vcpkg. It might take a few minutes to complete.

. (Optional) Add the vcpkg executable to your system's PATH environment variable. This step makes it easier to run vcpkg from any directory. Run the following command:

+
[source]
----
export PATH=$PATH:$(pwd)
----

+
To make this change permanent, add the above export command to your shell's configuration file, such as `~/.bashrc` or `~/.bash_profile` for the Bash shell.

. Now, vcpkg is installed on your Linux system, and you can start using it to manage your C++ project dependencies. To install a package, you can run a command like:

+
[source]
----
./vcpkg install <package-name>
----

+
Replace `<package-name>` with the name of the package you want to install.

. <<Verify your Boost Installation>>.

== Verify your Boost Installation

Once the installation is complete, the Boost libraries will be installed on your system, typically in */usr/include/boost* and */usr/lib64*(for 64-bit systems) or */usr/lib* (for 32-bit systems).

. To verify that the Boost libraries have been installed correctly, you can check the version number:

+
[source]
----
cat /usr/include/boost/version.hpp | grep "BOOST_LIB_VERSION"
----

+
This command should output the Boost version installed on your system.

. To use the libraries in your projects, you may need to configure your build system to include the appropriate header and library paths.

== Next Steps

xref:getting-started-with-linux.adoc#your-first-app[Your First App]