= Introduction to the Boost Release Process

The Boost libraries are released publicly three times per year:

[circle]
* 2nd April
* 2nd August
* 2nd December

Each release will contain updates to existing libraries, and some releases will contain new libraries. The release is built from the *master* branch of Boost's GitHub site:  xxxxxx

== Milestones in the Release Cycle

There is a strict countdown to a public release.

7 Weeks Prior to Release Date::

The *master* branch is closed to all check ins, except bug fixes and quality checks.

6 Weeks Prior to Release Date::

The *master* branch is closed to major code changes. There can be no rewrites of code, even to fix issues.

5 Weeks Prior to Release Date::

The *master* branch is closed to all check ins, except with permission from the release committee.

4 days Prior to Beta Release Date::

The *master* branch is closed. Beta release candidates are built.

4 Weeks Prior to Release Date::

The Beta release is published to the Boost site. The *master* branch is opened to small bug fixes and documentation changes. Permission from the release committee is required for larger changes.

1 Week Prior to Release Date::

The *master* branch is closed to all check ins, except high-priority fixes.

4 Days Prior to Release Date::

The *master* branch is closed. Release candidates are built.

Day of Release::

The release candidate is published to the Boost site. The *master* branch is opened for all check ins.

+
If issues are found with a release candidate that are important enough to address quickly (that is, before the next full public release), then a point release will be built when fixes are available and tested. This will not typically result in the *master* branch being closed to other check ins.

== See Also

* https://stage.antora.cppalliance.org/doc/user-guide/index.html[User Guide]
* https://stage.antora.cppalliance.org/doc/contributor-guide/index.html[Contributor Guide]
* https://stage.antora.cppalliance.org/doc/formal-reviews/intro.html[Formal Reviews]
