= Search Functionality

This document outlines the requirements and design of search functionality for Boost site documentation generated by Antora.

== Client-Side Search

With a client-side approach, a search index is built during the process of building a static website and loaded within the page in the browser. A Javascript search engine inside the browser responds to search queries without any server-side service.

Advantages of this approach include:

* It is very responsive because there is no request/response involved in the search process.
* There is no need for a server-side search engine and keep it updated with new content.
* Low maintenance cost because there is no load on the server to respond to search queries.
* It can work offline (considering that we can locally build reference documentation).

== Server-Side Search

With a server-side approach, all documents are indexed in a search engine, such as Elasticsearch, and a server-side service executes search requests on the search engine and returns results.

Advantages of this approach include:

* Wider search scopes: server-hosted search indices can be huge.
* Better results: because of more powerful cloud-computing resources.
* The possibility of semantic search.
* Analytics: server-collected statistics can be used to better serve users.

== Research

=== Antora Lunr Extension

https://gitlab.com/antora/antora-lunr-extension[Antora Lunr Extension] indexes content during builds and includes the index in published sites to provide a client-side full-text search.

Pros:

* Easy integration with Antora (minor changes to playbook.yaml and header-content.hbs).
* No need for a server-side service.
* Responsiveness as there is no request/response involved.
* Works offline.

Cons:

* A search option for all Boost libraries could lead to a large search-index.js file (around 100MB), making it impractical to deploy.
* No option to add metadata for categorizing search results in reference documentation.
* No semantic search functionality.

NOTE: Antora Lunr Extension is already integrated into the demo site https://docs.cppalliance.org/user-guide/index.html

=== Server-Side Solutions

==== DocSearch

Free Algolia search service for developer docs.

Requires investigation (http://docsearch.algolia.com/[link-to-website]).

==== Typesense

Open-source alternative to Algolia that can be deployed locally.

Requires investigation (https://typesense.org/[link-to-website]).

=== Reference Documentation in Other Languages

==== Docs.rs

Open-source documentation host for crates of the Rust Programming Language.

It uses a custom client-side search solution for searching in Reference Documentation. The search engine and indexing tools are implemented at https://github.com/rust-lang/rust/tree/master/src/librustdoc[librustdoc].

The search index contains metadata for identifier types:

[, Javascript]
----
const itemTypes = [
    "mod",
    "externcrate",
    "import",
    "struct",
    "enum",
    "fn",
    others...
];
----

The search results are narrowed down into Names, Parameters, and Return Types. An example of the search page (searching socket in the Tokio library) can be found at https://docs.rs/tokio/1.28.0/tokio/?search=socket.

The search-index.js file for each crate is not loaded until the user clicks on the search bar to reduce page size.
