////
Copyright (c) 2024 The C++ Alliance, Inc. (https://cppalliance.org)

Distributed under the Boost Software License, Version 1.0. (See accompanying
file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

Official repository: https://github.com/boostorg/website-v2-docs
////
= Boost Software License
:navtitle: Boost Software License

== FAQ


. *Where can I read the current version of the Boost Software License?*
+
Here: xref:user-guide:ROOT:bsl.adoc[The Boost Software License].

. *How should Boost programmers apply the license to source and header files?*
+
Add a multi-line comment based on the following template, substituting appropriate text for the name and date on the top line:
+
[source,cpp]
----
//          Copyright (c) 2004-2006 Joe Coder
// Distributed under the Boost Software License, Version 1.0.
//    (See accompanying file LICENSE_1_0.txt or copy at
//          https://www.boost.org/LICENSE_1_0.txt)
----
Notes::
+
a. Leave an empty line before and after the above comment block.
+
b. It is fine if the copyright and license messages are not on different lines; in no case should there be other intervening text.
+
c. Do not include "All rights reserved" anywhere.
+
d. Other ways of licensing source files have been considered, but some of them turned out to unintentionally nullify legal elements of the license. Having fixed language for referring to the license helps corporate legal departments evaluate the Boost distribution.
+
e. Creativity in license reference language is strongly discouraged, but judicious changes in the use of whitespace are fine.

. *How should the license be applied to documentation files rather than source files?*
+
Similarly to the way it is applied to source files: the user should see the very same text indicated in the template above, with the only difference that your local copy of LICENSE_1_0.txt should also be linked to.

. *How should Boost programmers maintain the copyright messages?*
+
Copyright is only claimed for changes meeting a certain threshold of originality. Therefore, the copyright message only covers expressions of creativity. It is up to authors of changes to add themselves to the copyright message if they so decide. Typically, a new claimant is added when someone takes over maintenance of a library or a new version of an existing library is developed. In principle, do not remove previous copyright claims - just add new claims and/or claimants.

. *How is the Boost Software License (BSL) different from the GNU General Public License (GPL)?*
+
The https://opensource.org/license/gpl-3-0[GNU General Public License] is longer, and may be harder to understand. The Boost license permits the creation of derivative works for any use with no legal requirement to release your source code. Other differences include BSL not requiring reproduction of copyright messages for object code redistribution, and the fact that BSL is not "viral": if you distribute your own code along with some Boost code, the BSL applies _only_ to the Boost code (and modified versions thereof); you are free to license your own code under any terms you like.

. *Why the phrase "machine-executable object code generated by a source language processor"?*
+
To distinguish cases where we do not require reproduction of the copyrights and license (such as object libraries, shared libraries, and final program executables), from cases where reproduction is still required (such as distribution of self-extracting archives of source code or precompiled header files). More detailed wording was rejected as not being legally necessary, and reducing readability.

. *Why is the "disclaimer" paragraph of the license entirely in uppercase?*
+
Capitalization of these particular provisions is a US legal mandate for consumer protection.

. *Does the copyright and license cover interfaces too?*
+
The conceptual interface to a library is _not_ covered. The particular representation expressed in the header is covered, as is the documentation, examples, test programs, and all the other material that goes with the library. A different implementation is free to use the same logical interface, however. Interface issues have been fought out in court several times; refer to a lawyer if this is likely to be an issue.

. *Why doesn't the license prohibit the copyright holder from patenting the covered software?*
+
No one who distributes their code under the terms of this license could turn around and sue a user for patent infringement. Boost's lawyers were well aware of patent provisions in licenses like the GPL and CPL, and would have included such provisions in the Boost license if they were believed to be legally useful.

. *Why doesn't the copyright message say "All rights reserved"?*
+
This provision does not belong in the copyright notice for anything (software, electronic documentation, etc.) that is being licensed. It belongs in books that are sold where, in fact, all rights (for example, to reproduce the book, etc.) are being reserved by the publisher or author.

. *Do I have to copyright/license trivial files?*
+
Yes, even a test file that just contains an empty `main()` should have a copyright notice. Files without copyright notices make corporate lawyers nervous, and that's a barrier to adoption. The more Boost is uniformly copyrighted and licensed, the better.

. *Can I use the Boost Software License for my own projects outside of Boost?*
+
Yes, there are no restrictions on the use of the license itself.

. *Is the Boost license Open Source?*
+
Yes. The https://opensource.org/[Open Source Initiative] certified the https://opensource.org/license/bsl-1-0[Boost Software License 1.0 in early 2008].



== See Also


* xref:contributors-faq.adoc[]

