////
Copyright (c) 2024 The C++ Alliance, Inc. (https://cppalliance.org)

Distributed under the Boost Software License, Version 1.0. (See accompanying
file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

Official repository: https://github.com/boostorg/website-v2-docs
////
= The Boost Steering Committee
:navtitle: Steering Committee

The https://groups.google.com/g/boost-steering?pli=1[_Boost Steering Committee_] is something of a misnomer as the committee plays a custodial and oversight role rather than being actively involved in "steering" the technical direction of the Boost pass:[C++] Libraries. Its primary function is to look after Boost's organizational, legal, and logistical assets, ensuring the community and its resources are well-supported for the long-term sustainability of the project.

The Boost Steering Committee _does not_ dictate the technical direction, nor development priorities, of individual libraries. Boost operates with a highly decentralized and community-driven development model, where individual contributors and maintainers have the autonomy to drive their libraries' progress. The Steering Committee supports this by ensuring the ecosystem remains healthy and sustainable for current and future contributors.

When referring to Boost "assets", these assets fall into five broad categories:

== 1. Trademark and Branding

The Boost name and logo are recognized worldwide within the pass:[C++] development community. The Steering Committee ensures that these are protected and used appropriately to maintain the reputation of the project. The Boost website, its domain (boost.org), and associated online content are managed to ensure accessibility and credibility.

== 2. Intellectual Property

The libraries themselves represent a significant intellectual asset, as they include contributions from many developers under xref:user-guide:ROOT:bsl.adoc[The Boost Software License (BSL)], or a similar open-source license. The Steering Committee ensures the letter and spirit of the license terms are upheld and remains compatible with Boost's goals of being free and open-source. The extensive and detailed documentation accompanying Boost libraries is an important part of the codebase, ensuring that developers can effectively use the libraries. 

== 3. Infrastructure

Boost's GitHub repositories are a critical part of its infrastructure. The committee helps ensure these resources are properly maintained and accessible to contributors. Boost's xref:testing/boost-test-matrix.adoc[test matrix] and automated build systems, particularly the xref:testing/continuous-integration.adoc[Continuous Integration (CI)] systems, are essential for quality assurance. The Steering Committee supports the infrastructure that allows library authors to ensure compatibility across compilers and platforms, and  oversees the mailing lists and communication channels used by the Boost community for development discussions.

== 4. Community and Governance

Boost's community of contributors and users is one of its most valuable assets. The Steering Committee provides governance to maintain the open, collaborative, and meritocratic culture of the project. This includes a role in the pass:[C++] community, including participation in conferences like https://cppnow.org/[C++ Now] (formerly BoostCon) and other events.

== 5. Financial and Legal Responsibilities

Boost operates as part of the https://cppalliance.org/[C++ Alliance], a non-profit organization that ensures proper legal and financial management of Boost resources. The Steering Committee collaborates with the Alliance on these matters. If funding or sponsorships are received (for example, for infrastructure or events), the Steering Committee helps ensure these are used appropriately.

== To Contact the Boost Steering Committee

The committee is currently a Google Group, refer to https://groups.google.com/g/boost-steering?pli=1[Boost Steering Committee].

== See Also

* xref:contributors-faq.adoc[]
* xref:getting-involved.adoc[]
* xref:user-guide:ROOT:bsl.adoc[]