= Documentation requiremens

@anarthal: this is taken verbatim from old content. It may be outdated.

Even the simplest library needs some documentation; the
 amount should be proportional to the need. The documentation
 should assume the readers have a basic knowledge of C++, but
 are not necessarily experts.


The format for documentation should be HTML, and should not
 require an advanced browser or server-side extensions. Style
 sheets are acceptable. ECMAScript/JavaScript is discouraged.
 The documentation entry point should always be a file named
 index.html; see [Redirection](#Redirection).


There is no single right way to do documentation. HTML
 documentation is often organized quite differently from
 traditional printed documents. Task-oriented styles differ from
 reference oriented styles. In the end, it comes down to the
 question: Is the documentation sufficient for the mythical
 "average" C++ programmer to use the library successfully?


Appropriate topics for documentation often include:


* General introduction to the library. The introduction
 particularly needs to include:
	+ A very high-level overview of what the library is
	 good for, and perhaps what it isn't good for,
	 understandable even by those with no prior knowledge of
	 the problem domain.
	+ The simplest possible ("hello world") example of
	 using the library.
* Tutorial covering basic use cases.
* Reference documentation:
	+ Description of each class.
	+ Relationship between classes.
	+ For each function, as applicable, description,
	 requirements (preconditions), effects, post-conditions,
	 returns, and throws.
	+ Discussion of error detection and recovery
	 strategy.
* How to compile and link.
* How to test.
* Version or revision history.
* Rationale for design decisions. See [Rationale rationale](#Rationale).
* Acknowledgements. See [Acknowledgments rationale.](#Acknowledgements)


If you need more help with how to write documentation you
 can check out the article on [Writing
 Documentation for Boost](../doc/libs/release/more/writingdoc/index.html).