////
Copyright (c) 2024 The C++ Alliance, Inc. (https://cppalliance.org)

Distributed under the Boost Software License, Version 1.0. (See accompanying
file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

Official repository: https://github.com/boostorg/website-v2-docs
////
= License Requirements
:navtitle: License Requirements

The preferred way to meet the license requirements is to use xref:user-guide:ROOT:bsl.adoc[]. See license information. If for any reason you do not intend to use the Boost Software License, please discuss the issues on the Boost developers mailing list first.

The license requirements:

[disc]
* Must be simple to read and understand.

* Must grant permission without fee to copy, use and modify the software for any use (commercial and non-commercial).

* Must require that the license appear on all copies of the software source code.

* Must not require that the license appear with executables or other binary uses of the library.

* Must not require that the source code be available for execution or other binary uses of the library.

* May restrict the use of the name and description of the library to the standard version found on the Boost web site.

== See Also

* xref:contributors-faq.adoc#boostsoftwarelicense[Contributors FAQ: Boost Software License]