= Definitions Template
:navtitle: Definitions

If you library uses any terminology that might benefit from a description, consider adding Definitions to your documentation.

Note that each definition is preceded by an anchor, so can be linked to from any other section of your documentation. This can help reduce duplication of explanations - link to your definitions rather than repeat explanations.

== AsciiDocs Source

[source,text]
----

==  <LibraryName> Definitions

Introductory text.

== Definitions

[#definition-term1]
*Term1*::
definition-text1

[#definition-term2]
*Term2*::
definition-text2

----

== Example

Assume there is a String-Container library.

==  Introduction to String-Container Definitions

String container algorithms work using some pre-defined concepts.

== Definitions

[#Finder Concept]
*Finder Concept*::
A Finder is a function which searches for an arbitrary part of a container. For example....

[#Formatter Concept]
*Formatter Concept*::
Formatters are used by string replace algorithms. For example....



Revised April, 2023

_Distributed under the Boost Software License, Version 1.0. (See
http://www.boost.org/LICENSE_1_0.txt)_.
