= Configuration Template

== \{\{Library}} Configuration

== Introduction

\{\{library}} uses several configuration macros in
http://www.boost.org/libs/config/config.htm[<boost/config.hpp>], as well as configuration macros meant to be supplied by the application. These
macros are documented here.

== Application Defined Macros

These are the macros that may be defined by an application using
\{\{library}}.

[cols=",",]
|===
|*Macro* |*Meaning*
|\{\{macro}} |\{\{meaning}}
|\{\{macro}} |\{\{meaning}}
|===

== Public Library Defined Macros

These macros are defined by \{\{library}} but are expected to be used by
application code.

[cols=",",]
|===
|*Macro* |*Meaning*
|\{\{macro}} |\{\{meaning}}
|\{\{macro}} |\{\{meaning}}
|===

== Library Defined Implementation Macros

These macros are defined by \{\{library}} and are implementation details
of interest only to implementers.

[cols=",",]
|===
|*Macro* |*Meaning*
|\{\{macro}} |\{\{meaning}}
|\{\{macro}} |\{\{meaning}}
|===

'''''

Revised 04 December, 2006

_Copyright © 2006 mailto:%7B%7Baddress%7D%7D[\{\{author}}]_

_Distributed under the Boost Software License, Version 1.0. (See
http://www.boost.org/LICENSE_1_0.txt)_.