////
Distributed under the Boost Software License, Version 1.0. (See accompanying
file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
Official repository: https://github.com/boostorg/website-v2-docs
////

== Version 1.91.0

boost_at:/doc/libs/1_91_0/[Documentation]

// Formatting reference: https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/
// Boost-specific macros: https://github.com/cppalliance/asciidoctor-boost?tab=readme-ov-file#macros
// Please keep the list of libraries sorted in lexicographical order.

== New Libraries

// Example:
// 
// * boost_phrase:library[Accumulators,/libs/accumulators]:
// ** Framework for incremental calculation, and collection of statistical
// accumulators, from Eric Niebler.

== Updated Libraries

// Example:
//  
// * boost_phrase:library[Interprocess,/libs/interprocess/]:
// ** Added anonymous shared memory for UNIX systems.
// ** Conform to `std::pointer_traits` requirements (boost_gh:pr[interprocess,32]).
// ** Fixed `named_condition_any` fails to notify (boost_gh:issue[interprocess,62]).

* boost_phrase:library[MultiIndex,/libs/multi_index/]:
** *Breaking change:* All type lists accepted or provided by the library (`indexed_by`,
`tag`, nested typedefs `index_specifier_type_list`, `index_type_list`, `iterator_type_list`
and `const_iterator_type_list`) are no longer based on boost_at:/libs/mpl[Boost.MPL] but
instead they are now boost_at:/libs/mp11/doc/html/mp11.html#definitions[Boost.Mp11 lists].
As a result, Boost.MultiIndex doesn't depend anymore on Boost.MPL. It is expected that
most user code won't be impacted by this change, but the previous behavior may be restored,
however, by globally defining the macro `BOOST_MULTI_INDEX_ENABLE_MPL_SUPPORT`. Legacy
support for Boost.MPL may be eventually deprecated and removed in the future.
** *Breaking change:* `composite_key` and associated class templates
(`composite_key_equal_to`, `composite_key_compare`, `composite_key_hash`) have been made
variadic (previously the maximum number of template arguments was limited by 
`BOOST_MULTI_INDEX_LIMIT_COMPOSITE_KEY_SIZE`). This change should be transparent to users, 
with the exception that `composite_key::key_extractors` returns a `std::tuple` instead of
a `boost::tuple` (and similarly for the rest of affected class templates).
** Removed internal workarounds and fallbacks to support pre-C++11 compilers.

== Compilers Tested

// Edit this section as appropriate

Boost's primary test compilers are:

* Linux:
** Clang, C++03: 3.4, 3.5, 3.6, 3.7, 3.8, 3.9, 12.0.0, 13.0.0, 14.0.0, 15.0.0
** Clang, C++11: 3.4, 11.0.0, 13.0.0, 14.0.0, 15.0.0
** Clang, C++14: 3.5, 3.6, 3.7, 3.8, 3.9, 4.0, 5.0, 12.0.0, 13.0.0, 14.0.0, 15.0.0
** Clang, C++17: 6.0.1, 7.0.0, 8.0.0, 9.0.0, 10.0.0, 11.0.0, 12.0.0, 13.0.0, 14.0.0, 15.0.0
** Clang, C++20: 11.0.0, 12.0.0, 13.0.0, 14.0.0, 15.0.0
** GCC, C++03: 4.6.3, 11, 12
** GCC, C++11: 4.7.3, 4.8.5, 11, 12
** GCC, C++14: 5.4.0, 6.4.0, 7.3.0, 8.0.1, 9.1.0, 11, 12
** GCC, C++17: 7.3.0, 8.0.1, 9.1.0, 11, 12
** GCC, C++20: 8.0.1, 9.1.0, 10, 11, 12
* OS X:
** Apple Clang, C++03: 11.0.3
** Apple Clang, C++11: 11.0.3
** Apple Clang, C++14: 11.0.3
** Apple Clang, C++17: 11.0.3
** Apple Clang, C++20: 11.0.3
* Windows:
** Visual C++: 10.0, 11.0, 12.0, 14.0, 14.1, 14.2, 14.3

== Acknowledgements

// Edit this section as appropriate

Marshall Clow, Glen Fernandes and Ion Gaztañaga managed this release.
