////
Distributed under the Boost Software License, Version 1.0. (See accompanying
file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
Official repository: https://github.com/boostorg/website-v2-docs
////

== Version 1.92.0

boost_at:/doc/libs/1_92_0/[Documentation]

// Formatting reference: https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/
// Boost-specific macros: https://github.com/cppalliance/asciidoctor-boost?tab=readme-ov-file#macros
// Please keep the list of libraries sorted in lexicographical order.

== General Notes

* In previous releases, Windows `.dll` files were installed by `b2 install`
into the library directory (`<PREFIX>/lib` by default), except on Cygwin,
where they were installed into the binary directory (`<PREFIX>/bin` by default.)
+
This has been changed to consistently install `.dll` files into the binary
directory, which is the behavior most users want.
+
For compatibility, a new command line option, `--dlldir`, has been added
to `b2 install` so that the directory can be overridden, and if needed,
pointed to `<PREFIX>/lib`.

* The CMake configuration file installed by `b2 install` has been updated
to support requesting header-only libraries as `find_package` components.
+
That is, something like `find_package(Boost REQUIRED COMPONENTS mp11)` works
now (and defines the target `Boost::mp11`), whereas previously it did not
(only compiled libraries were considered components).
+
This matches the behavior of the CMake configuration files installed by
building Boost with CMake, making it possible to consume Boost in the same
way regardless of how it was built and installed.
+
As part of this regularization, the little used feature of requesting
`COMPONENTS ALL` has been removed. It's not supported by the CMake Boost
build, and was never supported by `FindBoost`.

== New Libraries

// Example:
// 
// * boost_phrase:library[Accumulators,/libs/accumulators]:
// ** Framework for incremental calculation, and collection of statistical
// accumulators, from Eric Niebler.

== Updated Libraries

// Example:
//  
// * boost_phrase:library[Interprocess,/libs/interprocess/]:
// ** Added anonymous shared memory for UNIX systems.
// ** Conform to `std::pointer_traits` requirements (boost_gh:pr[interprocess,32]).
// ** Fixed `named_condition_any` fails to notify (boost_gh:issue[interprocess,62]).

* boost_phrase:library[Assert,/libs/assert/]:
** Fix `BOOST_VERIFY` in the rare case of both `BOOST_ENABLE_ASSERT_HANDLER` and `BOOST_ENABLE_ASSERT_DEBUG_HANDLER` being defined.

* boost_phrase:library[CointainerHash,/libs/container_hash/]:
** Hashing a valueless `std::variant` instance no longer throws.

* boost_phrase:library[Container,/libs/container/]:
** Added new `boost::container::hub` container designed by Joaquín M. López Muñoz.
+
See the Hub Container chapter in the Container documentation for more information.
** Fixed bugs/issues:
*** Wrong overload resolution protection in implementation of P2363R5 (boost_gh:issue[container,334]).
*** Compile error with `erase` and `small_vector<std::string>` (boost_gh:issue[container,336]).
*** `uses_allocator_construction.hpp`: missing `#include .../config_end.hpp` (boost_gh:issue[container,338]).
** Added `unchecked_emplace_back` and `unchecked_push_back` to `boost::container::vector`, `boost::container::static_vector`, and `boost::container::small_vector`.
** Implemented pass:[C++23] https://wg21.link/P1518[P1518] change: modified allocator-extended constructors for all containers so that the deduction guides for containers are not overconstrained.

* boost_phrase:library[Geometry,/libs/geometry/]:
** Improvements (`geometry`):
*** Drop `varray` implementation in favor of Boost.Container `static_vector` (boost_gh:pr[geometry,1458]).
*** Refactor/reduce misc boost dependencies (boost_gh:pr[geometry,1459]).
*** Improve short-distance accuracy of Andoyer inverse (boost_gh:pr[geometry,1461]).
** Solved issues (`geometry`):
*** Unit test `index_rtree_exceptions_rst` fails (boost_gh:issue[geometry,1399]).
*** Performance regression on GCC (boost_gh:issue[geometry,1452]).
*** Missing citation guidelines (boost_gh:issue[geometry,714]).
*** Two almost identical rectangles have no intersection (boost_gh:issue[geometry,1471]).
*** Various fixes of errors and warnings.

* boost_phrase:library[Hash2,/libs/hash2/]:
** Added built-in support for `std::optional`
** Added built-in support for `std::variant`, `std::monostate`

* boost_phrase:library[Heap,/libs/heap/]:
** This release is the last to support pass:[C++14]. Future releases will require pass:[C++17].

* boost_phrase:library[ICL,/libs/icl/]:
** Starting with version 22, pass:[libc++] has changed some lookup algorithms of its associative containers
in a way that breaks ICL's assumptions and behavior. The library internals
have been refactored to solve the problem and make ICL robust against future decisions of
the pass:[C++] committee regarding non-heterogeneous lookup for associative containers
(boost_gh:pr[icl,54], https://cplusplus.github.io/LWG/issue4572[LWG4752]).
** Fixed pass:[C++20]-related problems with `std::iter_value_t<element_iterator>` and GCC 10-12's
handling of rewritten relational operators (boost_gh:pr[icl,54]).
** Fixed a GCC 10-11 codegen bug (boost_gh:pr[icl,54]).

* boost_phrase:library[Interprocess,/libs/interprocess/]:
** Fixed bugs:
*** AIX build fix: fix return type in `get_invalid_systemwide_thread_id` (boost_gh:pr[interprocess,280]).
*** Locks in `message_queue_t` cover more code than intended (boost_gh:issue[interprocess,281]).

* boost_phrase:library[Lockfree,/libs/lockfree/]:
** This release is the last to support pass:[C++14]. Future releases will require pass:[C++17].
** Added new `boost::lockfree::mpsc_weak_queue`, a multi-producer, single-consumer queue.
   While `push` and `pop` are individually wait-free, the queue is not linearizable
   and a producer that stalls between exchanging the tail and linking its node can
   permanently break the queue, so it is not strictly lock-free.
** Added new `boost::lockfree::bounded_ticket_queue`, a ringbuffer-based bounded MPMC
   queue. The queue is linearizable and wait-free when configured with a single producer
   and single consumer. In multi-producer or multi-consumer configurations, a stalled
   thread that has claimed a slot can block progress, so the queue is not strictly
   lock-free.

* boost_phrase:library[Mp11,/libs/mp11/]:
** Improved the performance of a number of algorithms (contributed by Jonathan Poelen)

* boost_phrase:library[MSM,/libs/msm/]:
** New features (`backmp11`):
*** Provide an observer API for logging support (https://github.com/boostorg/msm/issues/220[#220])
*** Forward Kleene events to actions and guards without conversion (https://github.com/boostorg/msm/issues/229[#229])
*** Ensure basic exception guarantee and propagate exceptions to the caller (https://github.com/boostorg/msm/issues/221[#221])
*** Provide a reflection API and serialization support for Boost.Serialization, Boost.JSON and nlohmann/json (https://github.com/boostorg/msm/issues/197[#197])
*** Rework terminate and interrupt state handling and provide a `machine_state` enum (https://github.com/boostorg/msm/issues/244[#244])
*** Configurable event pool and inline storage (https://github.com/boostorg/msm/issues/239[#239])
*** API reference and examples are now available
** Bug fixes (`backmp11`):
*** State machine processes events although it is not running (https://github.com/boostorg/msm/issues/198[#198])
** **Breaking changes (`backmp11`)**:
*** Events in `process_event(...)` are not enqueued automatically anymore to reduce memory footprint, use `enqueue_event(...)` in actions (https://github.com/boostorg/msm/issues/178[#178])
*** The back-end does not forward constructor arguments to the front-end anymore, it must be default-constructible. To use custom constructors, define them in the back-end (https://github.com/boostorg/msm/issues/232[#232])
*** The deprecated APIs `process_queued_events()` and `process_single_queued_event()` are removed, use `process_event_pool(...)` instead
*** The default active state switch policy is set to "after source exit" in compliance to the UML specification. The other options are not UML-compliant and will be removed (https://github.com/boostorg/msm/issues/222[#222])
*** The back-end uses its own `process_result` type with new enum values instead of aliasing the enum of the `back` namespace. The old enum values are deprecated (https://github.com/boostorg/msm/issues/242[#242]) and will be removed
** fix(back, back11): Infinite recursion with event deferral in orthogonal regions (regression from 1.78) (https://github.com/boostorg/msm/issues/184[#184])

* boost_phrase:library[MultiIndex,/libs/multi_index/]:
** Fancy pointer support has been extended so that `multi_index_container` iterators now store
  references to the elements through the allocator's pointer type. In particular, this means that
  iterators can now be placed in shared memory using 
  boost_at:/libs/interprocess[Boost.Interprocess] allocators. 
** Fixed a performance issue with hashed indices when rehashing at very large container
  sizes (boost_gh:pr[multi_index,94]). Contributed by Daniel Kr&aacute;l.

* boost_phrase:library[System,/libs/system/]:
** Fix `unwrap_and_invoke` for functions returning `void`.

* boost_phrase:library[Unordered,/libs/unordered/]:
** Added interoperability with pass:[C++20] ranges to all the containers in the library:
   `insert_range` (plus `insert_range_(or|and)_[c]visit` for concurrent containers), 
   `std::from_range` construction and associated CTAD deduction guides. The
   `boost::unordered::from_range` construction tag is provided as an alternative to pass:[C++23]
   `std::from_range` or when this is not available.
** Fixed a performance issue with closed-addressing containers when rehashing at very large
   container sizes (boost_gh:pr[unordered,348]). Contributed by Daniel Kr&aacute;l.

== Compilers Tested

// Edit this section as appropriate

Boost's primary test compilers are:

* Linux:
** Clang, C++03: 3.4, 3.5, 3.6, 3.7, 3.8, 3.9, 12.0.0, 13.0.0, 14.0.0, 15.0.0
** Clang, C++11: 3.4, 11.0.0, 13.0.0, 14.0.0, 15.0.0
** Clang, C++14: 3.5, 3.6, 3.7, 3.8, 3.9, 4.0, 5.0, 12.0.0, 13.0.0, 14.0.0, 15.0.0
** Clang, C++17: 6.0.1, 7.0.0, 8.0.0, 9.0.0, 10.0.0, 11.0.0, 12.0.0, 13.0.0, 14.0.0, 15.0.0
** Clang, C++20: 11.0.0, 12.0.0, 13.0.0, 14.0.0, 15.0.0
** GCC, C++03: 4.6.3, 11, 12
** GCC, C++11: 4.7.3, 4.8.5, 11, 12
** GCC, C++14: 5.4.0, 6.4.0, 7.3.0, 8.0.1, 9.1.0, 11, 12
** GCC, C++17: 7.3.0, 8.0.1, 9.1.0, 11, 12
** GCC, C++20: 8.0.1, 9.1.0, 10, 11, 12
* OS X:
** Apple Clang, C++03: 11.0.3
** Apple Clang, C++11: 11.0.3
** Apple Clang, C++14: 11.0.3
** Apple Clang, C++17: 11.0.3
** Apple Clang, C++20: 11.0.3
* Windows:
** Visual C++: 10.0, 11.0, 12.0, 14.0, 14.1, 14.2, 14.3

== Acknowledgements

// Edit this section as appropriate

Marshall Clow, Glen Fernandes and Ion Gaztañaga managed this release.
