////
Distributed under the Boost Software License, Version 1.0. (See accompanying
file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
Official repository: https://github.com/boostorg/website-v2-docs
////

== Version 1.91.0

boost_at:/doc/libs/1_91_0/[Documentation]

// Formatting reference: https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/
// Boost-specific macros: https://github.com/cppalliance/asciidoctor-boost?tab=readme-ov-file#macros
// Please keep the list of libraries sorted in lexicographical order.

== New Libraries

// Example:
// 
// * boost_phrase:library[Accumulators,/libs/accumulators]:
// ** Framework for incremental calculation, and collection of statistical
// accumulators, from Eric Niebler.

* boost_phrase:library[Decimal,/libs/decimal]:
** An implementation of IEEE754 Decimal Floating Point Numbers, from Matt Borland and Christopher Kormanyos.

== Updated Libraries

// Example:
//  
// * boost_phrase:library[Interprocess,/libs/interprocess/]:
// ** Added anonymous shared memory for UNIX systems.
// ** Conform to `std::pointer_traits` requirements (boost_gh:pr[interprocess,32]).
// ** Fixed `named_condition_any` fails to notify (boost_gh:issue[interprocess,62]).

* boost_phrase:library[DynamicBitset,/libs/dynamic_bitset/]:
** Added a missing friend declaration for `operator-( const bit_iterator_base< Iter > & lhs, const bit_iterator_base< Iter > & rhs )`.
** Fixed compilation with standard library implementations which use raw pointers as iterators.
** Fixed `from_block_range()` to prevent it from setting any bit in the unused part of the bitset.

* boost_phrase:library[Exception,/libs/exception/]:
** Added customizable serialization API, built-in support for Boost.JSON and nlohmann/json.

* boost_phrase:library[LEAF,/libs/leaf/]:
** Added customizable serialization API, built-in support for Boost.JSON and nlohmann/json.
** Added support for using LEAF error objects across DLL boundaries on Windows (off by default).
** Refinements in the internal TLS API (e.g. Win32, embedded).
** Improvements in the diagnostics system and in the  `on_error` implementation.
** Implementation quality improvements (e.g. more precise use of `noexcept`).
** Removed the deprecated `verbose_diagnostic_info` (replaced by `diagnostic_details`).

* boost_phrase:library[MultiIndex,/libs/multi_index/]:
** *Breaking change:* All type lists accepted or provided by the library (`indexed_by`,
`tag`, nested typedefs `index_specifier_type_list`, `index_type_list`, `iterator_type_list`
and `const_iterator_type_list`) are no longer based on boost_at:/libs/mpl[Boost.MPL] but
instead they are now boost_at:/libs/mp11/doc/html/mp11.html#definitions[Boost.Mp11 lists].
As a result, Boost.MultiIndex doesn't depend anymore on Boost.MPL. It is expected that
most user code won't be impacted by this change, but the previous behavior may be restored,
however, by globally defining the macro `BOOST_MULTI_INDEX_ENABLE_MPL_SUPPORT`. Legacy
support for Boost.MPL may be eventually deprecated and removed in the future.
** *Breaking change:* `composite_key` and associated class templates
(`composite_key_equal_to`, `composite_key_compare`, `composite_key_hash`) have been made
variadic (previously the maximum number of template arguments was limited by 
`BOOST_MULTI_INDEX_LIMIT_COMPOSITE_KEY_SIZE`). This change should be transparent to users, 
with the exception that `composite_key::key_extractors` returns a `std::tuple` instead of
a `boost::tuple` (and similarly for the rest of affected class templates).
** Removed internal workarounds and fallbacks to support pre-C++11 compilers.

* boost_phrase:library[MSM,/libs/msm/]:
** New features (`backmp11`):
*** Improve support for the `deferred_events` property in hierarchical state machines (https://github.com/boostorg/msm/issues/173[#173])
*** Support conditional deferral with the `deferred_events` property (https://github.com/boostorg/msm/issues/155[#155])
*** Simplified functor signatures (https://github.com/boostorg/msm/issues/175[#175])
*** Merge queued and deferred events into a single event pool (https://github.com/boostorg/msm/issues/168[#168])
*** Small object optimization for events in the event pool (https://github.com/boostorg/msm/issues/172[#172])
*** Improve runtime performance with a `flat_fold` dispatch strategy (https://github.com/boostorg/msm/issues/180[#180])
*** Further optimize compilation, with up to 25% faster compile times and lower RAM consumption compared to version 1.90
** Bug fixes (`backmp11`):
*** Incorrect `FSM` type in calls to `on_entry(...)` and `on_exit(...)` (https://github.com/boostorg/msm/issues/167[#167])
*** Completion events fire too often (https://github.com/boostorg/msm/issues/166[#166])
** **Breaking change (`backmp11`)**: Direct access to the event pool is changed from `public` to `protected`,
because manipulating it outside of the library code can lead to undefined behavior.



* boost_phrase:library[Optional,/libs/optional/]:
** For compilers with full C++11 support (including "unrestricted  unions" and ref-qualifiers)
  changed the implementation from aligned storage to union storage. This enables the gradual
  `constexpr` support:

*** In C++11, some constructors and `const`-qualified accessors become usable
      in compile-time contexts (are _core constant expressions_) for types
      satisfying certain constraints.
*** In C++14 even some mutating operations become core constant expressions (those
      that do not require changing the state of `optional` from not having a value to
      having a value), for co-operating types.
*** In C++17 all constructors (including copy and move) become core constant expressions for co-operating types.

+

This addresses issues https://github.com/boostorg/optional/issues/132[#132] and https://github.com/boostorg/optional/issues/143[#143].

** *Breaking change.* Abandoned the mechanism for customizing
  `swap`. Hardly anyone knows about this mechanism and it was never documented.

** Applied a couple of small changes to get closer to the interface of `std::optional`:
  *** Enabled syntax `o = {}` for putting optional objects to no-value state.
  *** Enabled syntax `o.value_or({})`, which uses a default-constructed `T`.
  *** Construct `o = u`, where `o` is of type `optional<T>` and `u` is of type `U` convertible to `T`,
    does not create a temporary `T`.

** Added a conversion from `optional<T>&` to `optional<T&>`. This addresses https://github.com/boostorg/optional/issues/142[#142].

** `none_t` is now `std::equality_comparable`, which means that `none_t` and `optional<T>`
  model concept `std::equality_comparable_with` (for `std::equality_comparable` `T`),
  which means that you can `std::ranges::find(rng, boost::none)` for a range of optional objects.

** *Warning.* In the future releases we intend to introduce the range interface
  in `optional`, so that `std::ranges::range<optional<T>>` will be `true`.
  This will affect the overload resolution in programs in certain cases that make decisions based
  on predicates such as `std::ranges::range`. For instance, the following code
  will start behaving differently:

+

  template <typename T>
  void serialize(T const& v)
  {
    if constexpr (std::ranges::range<T>)
      serialize_as_range(v);
    else if constexpr (custom::is_optional_like<T>)
      serialize_as_optional(v);
    else
      serialize_as_value(v);
  }



* boost_phrase:library[Unordered,/libs/unordered/]:
** Fixed the returned value of range insertion in concurrent containers (boost_gh:pr[unordered,344]).

== Compilers Tested

// Edit this section as appropriate

Boost's primary test compilers are:

* Linux:
** Clang, C++03: 3.4, 3.5, 3.6, 3.7, 3.8, 3.9, 12.0.0, 13.0.0, 14.0.0, 15.0.0
** Clang, C++11: 3.4, 11.0.0, 13.0.0, 14.0.0, 15.0.0
** Clang, C++14: 3.5, 3.6, 3.7, 3.8, 3.9, 4.0, 5.0, 12.0.0, 13.0.0, 14.0.0, 15.0.0
** Clang, C++17: 6.0.1, 7.0.0, 8.0.0, 9.0.0, 10.0.0, 11.0.0, 12.0.0, 13.0.0, 14.0.0, 15.0.0
** Clang, C++20: 11.0.0, 12.0.0, 13.0.0, 14.0.0, 15.0.0
** GCC, C++03: 4.6.3, 11, 12
** GCC, C++11: 4.7.3, 4.8.5, 11, 12
** GCC, C++14: 5.4.0, 6.4.0, 7.3.0, 8.0.1, 9.1.0, 11, 12
** GCC, C++17: 7.3.0, 8.0.1, 9.1.0, 11, 12
** GCC, C++20: 8.0.1, 9.1.0, 10, 11, 12
* OS X:
** Apple Clang, C++03: 11.0.3
** Apple Clang, C++11: 11.0.3
** Apple Clang, C++14: 11.0.3
** Apple Clang, C++17: 11.0.3
** Apple Clang, C++20: 11.0.3
* Windows:
** Visual C++: 10.0, 11.0, 12.0, 14.0, 14.1, 14.2, 14.3

== Acknowledgements

// Edit this section as appropriate

Marshall Clow, Glen Fernandes and Ion Gaztañaga managed this release.
