////
Copyright (c) 2024 The C++ Alliance, Inc. (https://cppalliance.org)

Distributed under the Boost Software License, Version 1.0. (See accompanying
file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

Official repository: https://github.com/boostorg/website-v2-docs
////
= Release Notes

These are the release notes for *Boost version X.XX.XX*.

// Note the use of macros in square brackets [....]

== New Libraries

// List new libraries in lexicographical order:
// Example:
// * [phrase library..[@/libs/accumulators/ Accumulators]:] : performs incremental calculation, and collection of statistical accumulators, from Eric Niebler.

* [phrase library..[@/libs/charconv/ Charconv]:] A high quality implementation of `<charconv>` in C++11, from Matt Borland.
* [phrase library..[@/libs/scope/ Scope]:] A collection of scope guard utilities and a `unique_resource` wrapper, from Andrey Semashev.

== Updated Libraries

// List updated libraries in lexicographical order.
// Example:
// * [phrase library..[@/libs/<path>/ <Libname>]:]
// ** Dependency on Boost.TypeTraits removed
// ** Shared memory feature added
// ** Support for C++ 03 removed
// Mix and match the most relevant examples from below, and create an entry for your library:

* [phrase library..[@/libs/interprocess/ Interprocess]:]
** update 1 text
*** indented note for update 1, if needed
*** another indented note for update 1, if needed
** update 2 text  ([github_pr interprocess 32])
** update 3 text ([github_pr atomic 65])

* [phrase library..[@/libs/interprocess/ Interprocess]:]
** update 1 text
*** indented note for update 1, if needed
*** another indented note for update 1, if needed
** update 2 text ([github_pr bimap 42])
** update 3 text (thanks to [@https://github.com/13steinj 13steinj] for the report [github lexical_cast 64]!)

* [phrase library..[@/libs/wave/ Wave]:]
** Fixed bugs:
*** [github wave 200]: Emitted pragmas lack terminating newline
*** [github wave 202]: YYMARKER not updated when fill called on BOOST_WAVE_BSIZE boundary

* [phrase library..[@/libs/numeric/odeint/ Odeint]:]
 ** [*Breaking change]: The library now explicitly requires C++14 instead of implicitly by including Boost.Math

* [phrase library..[@/libs/msm/ MSM]:]
** [* Major Update]. Backend update (back11). Requires C++ 11. The documentation now uses it as default.
** [* Big new feature]. New front-end (PlantUML). Requires C++ 20 

* [phrase library..[@/libs/filesystem/ Filesystem]:]
** [*v4:] `equivalent` now indicates error if either one of the paths doesn't exist.

* [phrase library..[@/libs/geometry/ Geometry]:]
** Improvements
*** [github_pr geometry 1247] Use if constexpr macro instead of condition macro
** Solved issues
*** [github geometry 1231], [github geometry 1244] Fix invalid set operations for CCW polygons
*** [github geometry 1229] Fix union producing self intersections
*** [github_pr geometry 1248] Fix buffer issue by setting turns in closed clusters as non traversable
*** [github_pr geometry 1246] Fix compilation of converter and is_base_of

* [phrase library..[@/libs/mysql/ MySQL]:]
** [*Breaking change]: Boost.MySQL now requires linking to the new [*Boost.Charconv] compiled library.
*** This addresses a locale-dependency problem, increases efficiency, and powers the new client-side SQL formatting feature.
** Added experimental support for [*type-erased connections] (`any_connection` class).
*** `any_connection` is not a template and features simpler connection establishment and reconnection semantics.
** Added experimental support for [*client-side SQL formatting functions] (`format_sql` and `format_sql_to`).
*** These allow securely composing queries client-side, which enables patterns like batch inserts, dynamic filters or PATCH-like updates.

== Updated Tools

// Example:

* [phrase library..[@/tools/build/ Build]:]
** Includes release of [@/tools/build/doc/html/#_version_5_1_0 B2 version 5.1.0]

== Compilers Tested

// Edit this section as appropriate

Boost's primary test compilers are:

* *Linux*:
** Clang, C++03: 3.4, 3.5, 3.6, 3.7, 3.8, 3.9, 12.0.0, 13.0.0, 14.0.0, 15.0.0
** Clang, C++11: 3.4, 11.0.0, 13.0.0, 14.0.0, 15.0.0
** Clang, C++14: 3.5, 3.6, 3.7, 3.8, 3.9, 4.0, 5.0, 12.0.0, 13.0.0, 14.0.0, 15.0.0
** Clang, C++17: 6.0.1, 7.0.0, 8.0.0, 9.0.0, 10.0.0, 11.0.0, 12.0.0, 13.0.0, 14.0.0, 15.0.0
** Clang, C++20: 11.0.0, 12.0.0, 13.0.0, 14.0.0, 15.0.0

** GCC, C++03: 4.6.3, 11, 12
** GCC, C++11: 4.7.3, 4.8.5, 11, 12
** GCC, C++14: 5.4.0, 6.4.0, 7.3.0, 8.0.1, 9.1.0, 11, 12
** GCC, C++17: 7.3.0, 8.0.1, 9.1.0, 11, 12
** GCC, C++20: 8.0.1, 9.1.0, 10, 11, 12

* *OS X*:
** Apple Clang, C++03: 11.0.3
** Apple Clang, C++11: 11.0.3
** Apple Clang, C++14: 11.0.3
** Apple Clang, C++17: 11.0.3
** Apple Clang, C++20: 11.0.3

* *Windows*:
** Visual C++: 10.0, 11.0, 12.0, 14.0, 14.1, 14.2, 14.3

== Acknowledgements

// Example:  * Marshall Clow and Glen Fernandes managed this release.

* ack 1
* ack 2
