////
Copyright (c) 2024 The C++ Alliance, Inc. (https://cppalliance.org)

Distributed under the Boost Software License, Version 1.0. (See accompanying
file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

Official repository: https://github.com/boostorg/website-v2-docs
////
= Introduction to Boost Formal Reviews
:navtitle: Introduction

This Formal Review Guide provides information for the main roles in library submission:

. The authors who wish to submit the library to the Boost collection: refer to the xref:submissions.adoc[].
. The _Review Manager_ who's job it is to lead and coordinate the review process: refer to xref:managing-reviews.adoc[].
. The developers who test the submission, or elements of it, and write up their findings: refer to xref:writing-reviews.adoc[].

This guide also includes a comprehensive history of submissions, most with links to the rationale and announcements made during the evaluation process: refer to the xref:review-results.adoc[].

== Feedback

Feedback on any aspect of this documentation is encouraged, and is available by creating a https://github.com/cppalliance/site-docs/issues[New Issue].

== See Also

* xref:contributor-guide:ROOT:index.adoc[]
* xref:user-guide:ROOT:index.adoc[]
