= Introduction to Boost Formal Reviews

When you feel that your library is ready for entry into Boost,
 you need to find at least one member (but preferably several) of
 the Boost community who is willing to publicly endorse your
 library for entry into Boost. A simple method of achieving this
 is to post to the https://www.boost.org/community/groups.html[Boost
 developers mailing list] a short description of your
 library, links to its Github and documentation, and a request for
 endorsements.

It is expected that those who endorse a library for review
 will have performed at least a cursory check of the library's
 suitability for Boost in terms of documentation, fit with
 the rest of Boost and usefulness. A public endorsement of a
 library for review means that from an initial glance, they
 believe that the library has a reasonable chance to be accepted
 during a formal review. The expectation is that these endorsers
 will themselves review of the library during formal review
 period, though this is not binding.

Once you have a list of people who have publicly endorsed
 your library for review, email the https://www.boost.org/community/reviews.html#Wizard[Review Wizards] to request that your library be added to the https://www.boost.org/community/review_schedule.html[Boost Formal Review Schedule] where the following information will be shown:

[circle]
* Submission
* Submitter
* Links to Source (GitHub), Documentation (HTML website)
 and any Incubator entry
* Review Manager
* Review Dates


== Seek a Review Manager

In order to schedule a formal review, the author must find a
 capable volunteer to manage the review. This should be someone
 with knowledge of the library domain, and experience with the
 review process. See https://stage.antora.cppalliance.org/doc/formal-reviews/intro.html[Formal Reviews] for the responsibilities of the review manager.

Authors can find community members interested in managing
 reviews through discussion of the library on the developer
 list. If no one steps forward to volunteer to manage the
 review, it is appropriate to contact an experienced Boost
 member who showed interest in the library. Be considerate that
 managing a review is a serious commitment; for this reason,
 it's better to contact the member off-list.

If you cannot find a review manager after 3 weeks using the
 means above, and your submission is targeting eventual
 standardization, there is a list of Boost regulars who are also
 WG21 committee members who have volunteered to act as review
 managers in such cases. Please try them in the order listed:
 
 . Zach Laine
 . Micheal Caisse
 . Matt Calabrese
 . EdwardDiener
 . Louis Dionne
 . Vinnie Falco
 . Glen Fernandes
 . David Sankel


Once a potential review manager has been identified, contact the https://www.boost.org/community/reviews.html#Wizard[Review Wizards] for approval. The wizards approve review managers based on their level of participation in the Boost  community.

The review wizards will coordinate with both the author and
 review manager to schedule a date convenient for both.

== Formal Review

Before your formal review begins, double-, triple-, and
 quadruple-check your library. Verify that every code example
 works, that all unit tests pass on at least two compilers on at
 least two major operating systems, and run your documentation
 through a spelling and grammar checker.

Please do not modify your library on its *master* branch
 during a review. Instead, modify a separate *develop* branch in
 response to feedback and reviews. For bigger ticket items of
 work, open issues on your issue tracker so interested people can
 track the fixing of specific issues raised.

The review manager will consider all the reviews made by
 members of the community and arrive at a decision on
 whether your library is rejected, conditionally accepted or
 unconditionally accepted. They will post a report summarizing
 the decision publicly. If conditions are attached to
 acceptance, you will need to implement those conditions or
 else undergo an additional formal review.

== Boost web site posting

Once an accepted library is ready for inclusion on the Boost
 web site, the submitter is typically given Boost repository
 write access, and expected to check-in and maintain the library
 there. Contact the moderators if you need write access or
 direct use of the repository isn't possible for you.

== See Also

 * https://stage.antora.cppalliance.org/doc/user-guide/index.html[User Guide]
* https://stage.antora.cppalliance.org/doc/contributor-guide/index.html[Contributor Guide]
* https://stage.antora.cppalliance.org/doc/release-process/intro.html[Release Process]